export const cardServicos = [
  {
    key: '0',
    titulo: 'Manutenção industrial',
    icone: 'FaIndustry',
    descricao: `A GOIAS CALDEIRARIA, realiza trabalhos de caldeiraria mediante projetos desenvolvidos por seus clientes, como por exemplo: trocadores de calor, tubulações, tanques, mesas alimentadora, dornas, torres de resfriamento, estrutura metálica, dentre outros.`,
    className: 'card-servicos  animate__animated animate__backInLeft',
  },
  {
    key: '1',
    titulo: 'Manutenção agrícola',
    icone: 'FaTractor',
    descricao: `Realizamos todo tipo de Manutenção agrícola em equipamentos do tipo: Transbordo, roçadeira, hidrohal, subsolador, adubadora, uniport, colhedora, área de vivencia, caminhão baú oficina, trela canavieira dentre outros.`,
    className: 'card-servicos animate__animated animate__backInUp',
  },
  {
    key: '2',
    titulo: ' Caldeiraria',
    icone: 'FaFilter',
    descricao: `Realizamos diversos tipos de serviços de caldeiraria com pessoal qualificados para elaboração de peças em alto nível com detalhamento e precisão.`,
    className: 'card-servicos animate__animated animate__backInUp',
  },
  {
    key: '3',
    titulo: ' Soldagens em geral',
    icone: 'FaFireAlt',
    descricao: `Realizamos diversos tipos de Solda com pessoal treinado e qualificados em diversas áreas de atuação.`,
    className: 'card-servicos animate__animated animate__backInRight',
  },
];

export const ProdServico = [
  {
    key: '0',
    titulo: `Tanque Industrial`,
    orderImg: '1',
    orderText: '2',
    srcImg: '/tanque.jpg',
    descricao: ``,
    className: 'Image-servico',
  },
  {
    key: '1',
    titulo: `Manutenção de Maquinário Agrícola`,
    orderImg: '2',
    orderText: '1',
    srcImg: '/colhedora.jpg',
    descricao: ``,
    className: 'Image-servico1',
  },
  {
    key: '2',
    titulo: `Manutenção em Trelas conjunto canavieiro`,
    orderImg: '1',
    srcImg: '/trela.png',
    orderText: '2',
    descricao: ``,
    className: 'Image-servico2',
  },
];
export const HeaderText = [
  {
    key: '0',
    text: 'Manutenção industrial',
  },
  {
    key: '1',
    text: 'Manutenção agrícola',
  },
  {
    key: '2',
    text: 'Caldeiraria',
  },
  {
    key: '3',
    text: 'Soldagens em geral',
  },
];
export const Parceiros = [
  {
    key: '0',
    src: '/gafor.png',
    order: '0',
    background: '',
    width: 1000,
    height: 250,
    base: '800px',
    md: '400px',
    lg: '400px',
    xl: '600px',
    alt: 'gafor',
  },
  {
    key: '1',
    src: '/atvos.png',
    order: '1',
    background: '',
    width: 1000,
    height: 250,
    base: '800px',
    md: '400px',
    lg: '400px',
    xl: '600px',
    alt: 'atvos',
  },
  {
    key: '2',
    src: '/conlog.png',
    order: '2',
    background: '#c4302b',
    width: 1000,
    height: 250,
    base: '800px',
    md: '400px',
    lg: '400px',
    xl: '600px',
    alt: 'conlog',
  },
  {
    key: '3',
    src: '/jsl.png',
    order: '3',
    background: '#c4302b',
    width: 1000,
    height: 250,
    base: '800px',
    md: '400px',
    lg: '400px',
    xl: '600px',
    alt: 'jsl',
  },
  {
    key: '4',
    src: '/marfrig.svg',
    order: '4',
    background: '',
    width: 1000,
    height: 250,
    base: '800px',
    md: '400px',
    lg: '400px',
    xl: '600px',
    alt: 'marfrig',
  },
];
